[versions]
agp = "8.4.0"
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
googleServices = "4.4.2"
crashlytics = "3.0.2"
firebaseAppdistribution = "5.0.0"
applovin = "13.4.0.0"
applovinSdk = "13.4.0"
facebook = "6.20.0.1"
facebookSdk = "latest.release"
pangle = "7.6.0.3.0"
mintegral = "16.9.91.1"
firebaseBom = "33.3.0"
gson = "2.11.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
junitver = "1.2.1"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.8.1"
activityCompose = "1.9.0"
composeBom = "2023.08.00"
hiltVersion = "2.47"
appcompat = "1.7.0"
intuitSdp = "1.1.1"
googleMaterial = "1.12.0"
airbnbLottie = "6.4.1"
activity = "1.9.0"
constraintlayout = "2.1.4"
googlePlayReview = "2.0.1"
playServicesAds = "24.5.0"
playServicesVision = "18.0.0"
purchases = "7.10.1"
purchasesVersion = "7.0.0"
sdkAndroid = "4.7.1"
shimmer = "0.5.0"
firebaseMessaging = "24.0.1"
userMessagingPlatform = "3.0.0"
navigationFragment = "2.8.5"
navigationUi = "2.8.5"
work = "2.10.5"
room = "2.8.1"
retrofit = "2.9.0"
okhttp = "4.12.0"
cameraview = "2.7.2"
dotsindicator = "5.1.0"
unityAds = "4.16.1"
unityMediation = "4.16.1.0"
vungleMediation = "7.5.1.0"
inmobiMediation = "10.8.8.1"
ironsourceMediation = "9.0.0.1"
molocoMediation = "4.1.1.0"
applovinGoogleAdapter = "24.5.0.0"
applovinFacebookAdapter = "6.20.0.0"
applovinBytedanceAdapter = "7.6.0.3.0"
applovinMintegralAdapter = "16.9.91.0"
applovinUnityAdapter = "4.16.1.0"
glide = "5.0.0-rc01"

[libraries]
# Core Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-multidex = "androidx.multidex:multidex:2.0.1"

# Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "room" }
lifecycle-extensions = "android.arch.lifecycle:extensions:1.1.1"
lifecycle-compiler = "android.arch.lifecycle:compiler:1.1.1"

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Hilt/Dagger
google-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-analytics-ktx = "com.google.firebase:firebase-analytics-ktx:21.3.0"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-crashlytics-ktx = "com.google.firebase:firebase-crashlytics-ktx:18.4.1"
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-database = "com.google.firebase:firebase-database:20.2.2"

# Google Play Services & Review
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-vision = { module = "com.google.android.gms:play-services-vision", version.ref = "playServicesVision" }
play-review-ktx = "com.google.android.play:review-ktx:2.0.1"
google-play-core-review = { group = "com.google.android.play", name = "review", version.ref = "googlePlayReview" }
user-messaging-platform = { module = "com.google.android.ump:user-messaging-platform", version.ref = "userMessagingPlatform" }

# UI Libraries
bumptech-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
airbnb-lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "airbnbLottie" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
powermenu = "com.github.skydoves:powermenu:2.2.0"
spinkit = "com.github.ybq:Android-SpinKit:1.4.0"
ratingbar = "com.github.yangmbin:RatingBar:1.0.0"
intuit-sdp = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "intuitSdp" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }

# Navigation
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

# Networking & Data
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
rxjava = "io.reactivex.rxjava3:rxjava:3.0.12"
rxandroid = "io.reactivex.rxjava3:rxandroid:3.0.0"
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

# Work Manager
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

# Localization
localization = "com.akexorcist:localization:1.2.10"

# Permissions
dexter = "com.karumi:dexter:6.2.3"

# Facebook
facebook-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookSdk" }
audience-network-sdk = "com.facebook.android:audience-network-sdk:6.17.0"

# Ad Mediation - Google AdMob Adapters
facebook-mediation = { module = "com.google.ads.mediation:facebook", version.ref = "facebook" }
applovin-mediation = { module = "com.google.ads.mediation:applovin", version.ref = "applovin" }
vungle-mediation = { module = "com.google.ads.mediation:vungle", version.ref = "vungleMediation" }
pangle-mediation = { module = "com.google.ads.mediation:pangle", version.ref = "pangle" }
mintegral-mediation = { module = "com.google.ads.mediation:mintegral", version.ref = "mintegral" }
unity-ads = { module = "com.unity3d.ads:unity-ads", version.ref = "unityAds" }
unity-mediation = { module = "com.google.ads.mediation:unity", version.ref = "unityMediation" }
inmobi-mediation = { module = "com.google.ads.mediation:inmobi", version.ref = "inmobiMediation" }
ironsource-mediation = { module = "com.google.ads.mediation:ironsource", version.ref = "ironsourceMediation" }
moloco-mediation = { module = "com.google.ads.mediation:moloco", version.ref = "molocoMediation" }

# AppLovin MAX
applovin-sdk = { module = "com.applovin:applovin-sdk", version.ref = "applovinSdk" }
applovin-google-adapter = { module = "com.applovin.mediation:google-adapter", version.ref = "applovinGoogleAdapter" }
applovin-facebook-adapter = { module = "com.applovin.mediation:facebook-adapter", version.ref = "applovinFacebookAdapter" }
applovin-bytedance-adapter = { module = "com.applovin.mediation:bytedance-adapter", version.ref = "applovinBytedanceAdapter" }
applovin-mintegral-adapter = { module = "com.applovin.mediation:mintegral-adapter", version.ref = "applovinMintegralAdapter" }
applovin-unity-adapter = { module = "com.applovin.mediation:unityads-adapter", version.ref = "applovinUnityAdapter" }

# Solar Engine
solar-engine = "com.reyun.solar.engine.oversea:solar-engine-core:1.2.9.2"

# Annotations
androidx-annotation = "androidx.annotation:annotation:1.0.0"

# RevenueCat
purchases = { module = "com.revenuecat.purchases:purchases", version.ref = "purchases" }
purchases-v700 = { module = "com.revenuecat.purchases:purchases", version.ref = "purchasesVersion" }

# Airbridge
sdk-android = { module = "io.airbridge:sdk-android", version.ref = "sdkAndroid" }

# Camera
cameraview = { module = "com.otaliastudios:cameraview", version.ref = "cameraview" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitver" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
google-firebase-appdistribution = { id = "com.google.firebase.appdistribution", version = "5.0.0" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version = "2.1.0-1.0.29" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }